// flow-typed signature: a59b8771aecc2946ce76cb355d5a8407
// flow-typed version: <<STUB>>/pnp-webpack-plugin_v1.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pnp-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pnp-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pnp-webpack-plugin/index' {
  declare module.exports: $Exports<'pnp-webpack-plugin'>;
}
declare module 'pnp-webpack-plugin/index.js' {
  declare module.exports: $Exports<'pnp-webpack-plugin'>;
}
