// flow-typed signature: c687d94158485eaeea22c3fdd14d4e41
// flow-typed version: <<STUB>>/react-circular-graph_v^1.0.6/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-circular-graph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-circular-graph' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-circular-graph/index' {
  declare module.exports: $Exports<'react-circular-graph'>;
}
declare module 'react-circular-graph/index.js' {
  declare module.exports: $Exports<'react-circular-graph'>;
}
