// flow-typed signature: 7d825e3c937e05043f6a761578b48e66
// flow-typed version: <<STUB>>/vis-react_v^0.4.2/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vis-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vis-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vis-react/index' {
  declare module.exports: $Exports<'vis-react'>;
}
declare module 'vis-react/index.js' {
  declare module.exports: $Exports<'vis-react'>;
}
